### ISSUE TITLE
Failure on inserting any songs

### ISSUE THREAD

**Issue by Kyrari** [crazoter/Genshin-Lyre-Overlay#13]
I'd keep getting an exception tkinter issues and already tried downloading the newest python packages 3.9.5, this happens on every sample songs so I can't tell if I'm missing any requirements or it's the app.
![tkinter](https://user-images.githubusercontent.com/70010431/117562560-ffb68980-b0c9-11eb-9aac-861dac5b2401.png)

**Comment by Heronickproductions** [comment]
same problem here

**Comment by crazoter** [comment]
Oh dear, I didn't see these issues. Sorry for the late response, the distributed exe does appear to be bugged even though the script version is working properly. I'll debug and get around to this.

**Comment by crazoter** [comment]
I realized what's the issue. The config file I shipped with the distribution exe provided too small a screen size, which exposed a bug that occurred when the screen size was too small. I fixed that bug, and changed the config in the dist exe.

Again, apologies for not seeing this issue. Next time if you encounter a problem / have any queries and I don't respond, feel free to:
1. Drop me a private message on Discord; my account handle is Thrice Reckless Mad Saber#6645.
2. Email me directly at crazoter@gmail.com

Edit: the new exe and config file is now updated in the release section. You can redownload at https://github.com/crazoter/Genshin-Lyre-Overlay/releases/tag/2.1

**Comment by crazoter** [comment]
This issue has been resolved but I'll leave it open for the time being in case there's any need for follow-up.
