### ISSUE TITLE
Ordering of buttons in Keyboard mode

### ISSUE THREAD

**Issue by crazoter** [crazoter/Genshin-Lyre-Overlay#5]
Edit: I'm thinking of color coding the notes based on which hand is closer to the key. Will see

**Comment by l-4k-l** [comment]
Yes, the octave is in reverse! I also realised. It's still a very ambitious program and I very much support what you're doing here.

**Comment by crazoter** [comment]
Improved. I realize that players will be using the keyboard, not the piano, so I reordered & color coded it according to left & right hand, while also including the clef for clarity.

![image](https://user-images.githubusercontent.com/9276766/113092018-c3b51c80-921f-11eb-9b6b-2985b9920731.png)

I think this is good enough (or even optimal), but will leave this issue open for discussion and feedback as users stream in.

**Comment by crazoter** [comment]
Closed as I think there is no need for further discussion at this juncture.
